[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"


[project]
name = "your_package_name"
version = "0.0.1"
description = "A short description of your library or package"
readme = "README.md"
requires-python = ">=3.8"
license = { text = "MIT" }
keywords = ["example", "library", "package"]
authors = [{ name = "Darshil Jani", email = "darshiljani.dev@gmail.com" }]

[tool.setuptools.packages.find]
where = ["src"]

[project.optional-dependencies]
dev = ["mypy", "ruff", "pre-commit"]

[project.scripts]
pkg-test = "pkg_name.tests.runner:main"

[tool.coverage.run]
branch = true
source = ["src"]
omit = ["*/tests/*", "*/__init__.py"]


[tool.mypy]
strict = true
ignore_missing_imports = true
disallow_untyped_defs = true
disallow_any_unimported = true
warn_unused_ignores = true
warn_return_any = true
exclude = ["tests/"]
